- descriptor: "pip-services-commons:logger:console:*:*"
  type: "PipServices.Commons,PipServices.Commons.Log.ConsoleLogger"
  level: "trace"

- descriptor: "pip-services-dummies:controller:*:*:*"
  type: "PipServices.Container.Test,PipServices.Container.DummyController"
  message: "Hello from dummy controller #1"