- descriptor: "pip-services-commons:logger:console:*:*"
  level: "trace"

- descriptor: "pip-services-dummies:controller:*:*:*"
  message: "Hello from dummy controller #1"

- descriptor: "pip-services-container:container-info:*:*:*"
  message: "Hello from dummy controller #2"